export const casualCopy = {
  pageTitle: "Play a casual game",
  pageDescription: "Start and share a casual scorecard in seconds.",
  hostPageTitle: "Casual game controls",
  watchPageTitle: "Watch a casual game",
  eyebrow: "PLAY TOGETHER",
  setupTitle: "A game in seconds.",
  setupIntro: "Choose your sport, set the rules, and keep score from one screen. Guests can start immediately.",
  sport: "Sport",
  teamA: "First side",
  teamB: "Second side",
  target: "Points to win a set",
  sets: "Best of sets",
  period: "Period length (minutes)",
  start: "Start game",
  starting: "Starting…",
  guestNote: "Your control stays on this browser. Share the separate viewing link with friends.",
  signIn: "Sign in to save across devices",
  live: "LIVE GAME",
  finished: "FINAL SCORE",
  scoreHint: "Tap a side to add a point",
  elapsed: "Elapsed",
  set: "Set",
  periodLabel: "Period length",
  undo: "Undo last point",
  pause: "Pause timer",
  resume: "Resume timer",
  finish: "Finish game",
  share: "Share viewing link",
  copied: "Viewing link copied",
  copy: "Copy link",
  close: "Close",
  viewerNote: "Friends can watch this game. Only the host can change the score.",
  watch: "WATCHING LIVE",
  watchFinal: "FINAL SCORE",
  update: "Updated",
  reconnecting: "Reconnecting…",
  goBack: "New game",
  confirmFinish: "Finish this game? Scoring and the timer will stop.",
  noAccess: "Host controls are available only on the browser that started this game.",
  unavailable: "This game is unavailable right now.",
  accountTitle: "Your games",
  sharedGames: "Shared with you",
  sharedEmpty: "Games shared by friends will appear here.",
  accountIntro: "Sign in to keep games and presets across devices, and share with accepted friends.",
  saveGame: "Save this game to my account",
  saved: "Saved to your account",
  savePreset: "Save these settings as a preset",
  presets: "Saved settings",
  choosePreset: "Use saved settings",
  historyEmpty: "No saved games yet. Start one above.",
  friends: "Friends",
  friendHint: "Friend requests need acceptance before you can share a game.",
  friendAccount: "Friend account ID",
  friendEmail: "Friend email",
  sendRequest: "Send friend request",
  pending: "Pending requests",
  accept: "Accept",
  shareFriend: "Share with friend",
  liveClock: "Live clock",
  shareableView: "Shareable view",
  setupLabel: "Set up a casual game",
  setupStep: "01 / GAME SETUP",
  makeYours: "Make it yours",
  yourSpace: "YOUR SPACE",
  startFailed: "Could not start the game.",
  presetSaved: "Preset saved to your account.",
  presetFailed: "Could not save the preset.",
  game: "Game",
  liveLabel: "Live",
  finalLabel: "Final",
  currentScore: "Current score",
  pointAdded: "+1 point",
  watching: "Watching",
  setScores: "Set scores",
  shareMoment: "SHARE THE MOMENT",
  loading: "Loading game…",
  missingViewingLink: "Viewing link is unavailable. Refresh and try again.",
  connect: "CONNECT",
  friendSent: "Friend request sent.",
  friendSendFailed: "Could not send request.",
  friendAccepted: "Friend request accepted.",
  friendAcceptFailed: "Could not accept request.",
} as const;
