export const scoringControlPanelCopy = {
  liveControls: "Live controls",
  controlPanel: "Control panel",
  currentScore: "Current score",
  score: "Score",
  scoreHint: "Choose scoring action",
  card: "Card",
  cardHint: "Select card and team",
  timeout: "Timeout",
  timeoutHint: "Select timeout and team",
  event: "Event",
  eventHint: "Record an incident or match event",
  other: "Other",
  otherHint: "Segment and exceptional outcomes",
  addTimeAndPlayer: "Add time and player",
  detailsHint: "Tap an event. The next card collects the time, team and player details.",
  chooseCategory: (category: string) => `Choose ${category.toLowerCase()}`,
  pickerDescription: "Select the exact event, then add the match time and participant details.",
  wholeMatch: "Whole match",
  close: "Close",
  matchEventsOpen: "Match events open",
  swipeDownForEvents: "Swipe down for match events",
  recordedEvents: (count: number) => `${count} recorded ${count === 1 ? "event" : "events"}`,
  tapAlsoWorks: "tap also works",
  closeMatchEvents: "Close match events",
  closeEvents: "Close events",
} as const;
