export const ErrorCode = {
  // Authentication & Authorisation
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  ACCESS_DENIED: "ACCESS_DENIED",
  ORGANISATION_ACCESS_DENIED: "ORGANISATION_ACCESS_DENIED",
  COMPETITION_ACCESS_DENIED: "COMPETITION_ACCESS_DENIED",
  PLATFORM_ADMIN_REQUIRED: "PLATFORM_ADMIN_REQUIRED",
  STEP_UP_REQUIRED: "STEP_UP_REQUIRED",
  CSRF_INVALID: "CSRF_INVALID",
  ORIGIN_REJECTED: "ORIGIN_REJECTED",

  // Concurrency & Conflicts
  REVISION_CONFLICT: "REVISION_CONFLICT",
  IDEMPOTENCY_MISMATCH: "IDEMPOTENCY_MISMATCH",
  IDEMPOTENCY_KEY_REUSED: "IDEMPOTENCY_KEY_REUSED",
  COMPETITION_ARCHIVED: "COMPETITION_ARCHIVED",
  COMPETITION_SLUG_TAKEN: "COMPETITION_SLUG_TAKEN",
  TEMPLATE_ARCHIVED: "TEMPLATE_ARCHIVED",
  ACTIVE_SCHEDULE_JOB: "ACTIVE_SCHEDULE_JOB",
  SCHEDULE_LOCK_CONFLICT: "SCHEDULE_LOCK_CONFLICT",
  FORMAT_RECOMMENDATION_CONFLICT: "FORMAT_RECOMMENDATION_CONFLICT",
  FORMAT_RECOMMENDATION_STALE: "FORMAT_RECOMMENDATION_STALE",
  FORMAT_MATERIALISATION_INCOMPLETE: "FORMAT_MATERIALISATION_INCOMPLETE",
  RECOMMENDATION_EVIDENCE_NOT_FOUND: "RECOMMENDATION_EVIDENCE_NOT_FOUND",

  // Stale References
  STALE_CAPACITY_REFERENCE: "STALE_CAPACITY_REFERENCE",
  STALE_SETTINGS_REFERENCE: "STALE_SETTINGS_REFERENCE",
  STALE_ENTRIES_REFERENCE: "STALE_ENTRIES_REFERENCE",
  STALE_FORMAT_REFERENCE: "STALE_FORMAT_REFERENCE",
  STALE_RECOMMENDATION_EVIDENCE: "STALE_RECOMMENDATION_EVIDENCE",
  STALE_SCHEDULE_REFERENCE: "STALE_SCHEDULE_REFERENCE",

  // Domain Validation & Pre-requisites
  DOMAIN_VALIDATION_FAILED: "DOMAIN_VALIDATION_FAILED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  IMPORT_VALIDATION_FAILED: "IMPORT_VALIDATION_FAILED",
  FREE_ENTRY_LIMIT_REACHED: "FREE_ENTRY_LIMIT_REACHED",
  REQUEST_INVALID: "REQUEST_INVALID",
  FORMAT_PREREQUISITE_MISSING: "FORMAT_PREREQUISITE_MISSING",
  FORMAT_RECOMMENDATION_NOT_FITTING: "FORMAT_RECOMMENDATION_NOT_FITTING",
  FORMAT_INVALID: "FORMAT_INVALID",
  FORMAT_ENTRY_COUNT_MISMATCH: "FORMAT_ENTRY_COUNT_MISMATCH",
  SETUP_PREREQUISITE_MISSING: "SETUP_PREREQUISITE_MISSING",
  SETUP_STEP_INVALID: "SETUP_STEP_INVALID",
  SETUP_INCOMPLETE: "SETUP_INCOMPLETE",

  // Resource Not Found
  NOT_FOUND: "NOT_FOUND",
  COMPETITION_NOT_FOUND: "COMPETITION_NOT_FOUND",
  DIVISION_NOT_FOUND: "DIVISION_NOT_FOUND",
  MATCH_NOT_FOUND: "MATCH_NOT_FOUND",
  FORMAT_REVISION_NOT_FOUND: "FORMAT_REVISION_NOT_FOUND",
  SCHEDULE_REVISION_NOT_FOUND: "SCHEDULE_REVISION_NOT_FOUND",
  SCHEDULE_JOB_NOT_FOUND: "SCHEDULE_JOB_NOT_FOUND",
  ACCESS_PASS_NOT_FOUND: "ACCESS_PASS_NOT_FOUND",

  // Rate Limiting & Infra
  RATE_LIMITED: "RATE_LIMITED",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_CAPACITY_REVISION: "INVALID_CAPACITY_REVISION",
} as const;

export type ApiErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
