#!/usr/bin/env bash
# MATCHDAY production Postgres backup.
#
#   matchday-backup.sh backup                  nightly: pg_dump -> (age) -> Object Storage -> verify -> prune
#   matchday-backup.sh upload-snapshot FILE    upload a pre-migration dump made by deploy-prod.sh
#
# Runs inside the `backup` compose service (see compose.prod.yaml). Any failure exits
# non-zero, prints "ERROR:" / "BACKUP_STATUS=failed" and records status/status.json so an
# external monitor can alert. Success touches status/last-success.
set -euo pipefail

LOG_TAG="backup"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
. "$SCRIPT_DIR/lib.sh"

BACKUP_DIR="${BACKUP_DIR:-/backups}"
STATUS_DIR="$BACKUP_DIR/status"
LOCAL_RETAIN="${BACKUP_LOCAL_RETAIN:-3}"
RETAIN_DAILY="${BACKUP_RETAIN_DAILY:-14}"
RETAIN_WEEKLY="${BACKUP_RETAIN_WEEKLY:-8}"
RETAIN_PREMIGRATION="${BACKUP_RETAIN_PREMIGRATION:-10}"
MAX_TOTAL_BYTES="${BACKUP_MAX_TOTAL_BYTES:-16106127360}" # 15 GiB: headroom under the 20 GB free tier
COMMAND="${1:-backup}"
STARTED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
START_EPOCH="$(date -u +%s)"
SUCCEEDED=0
LAST_KEY=""
LAST_BYTES=0
LAST_SHA=""

write_status() { # STATUS MESSAGE
  local status="$1" message="$2"
  mkdir -p "$STATUS_DIR" 2>/dev/null || return 0
  printf '{"status":"%s","command":"%s","started_at":"%s","finished_at":"%s","duration_seconds":%s,"key":"%s","bytes":%s,"sha256":"%s","message":"%s"}\n' \
    "$status" "$COMMAND" "$STARTED_AT" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$(($(date -u +%s) - START_EPOCH))" \
    "$LAST_KEY" "$LAST_BYTES" "$LAST_SHA" "$(printf '%s' "$message" | tr -d '"\\' | tr '\n' ' ')" \
    >"$STATUS_DIR/status.json.tmp" && mv "$STATUS_DIR/status.json.tmp" "$STATUS_DIR/status.json" || true
}

ping_heartbeat() { # "" | /fail
  [ -n "${BACKUP_HEARTBEAT_URL:-}" ] || return 0
  curl --silent --show-error --fail --max-time 15 --retry 2 "${BACKUP_HEARTBEAT_URL%/}$1" >/dev/null ||
    warn "heartbeat ping to BACKUP_HEARTBEAT_URL$1 failed"
}

on_exit() {
  local rc=$?
  trap - EXIT
  if [ "$rc" -eq 0 ] && [ "$SUCCEEDED" -eq 1 ]; then
    write_status ok "completed"
    : >"$STATUS_DIR/last-success" 2>/dev/null || true
    log "BACKUP_STATUS=ok key=$LAST_KEY bytes=$LAST_BYTES"
    ping_heartbeat ""
    exit 0
  fi
  [ "$rc" -ne 0 ] || rc=1
  write_status failed "see container logs"
  printf '[%s] %s ERROR: BACKUP_STATUS=failed command=%s exit=%s\n' "$LOG_TAG" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$COMMAND" "$rc" >&2
  ping_heartbeat "/fail"
  exit "$rc"
}
trap on_exit EXIT

validate_recipients() {
  local recipient
  IFS=',' read -r -a RECIPIENTS <<<"${BACKUP_AGE_RECIPIENT:-}"
  for recipient in "${RECIPIENTS[@]}"; do
    [[ "$recipient" =~ ^age1[a-z0-9]{58}$ ]] || die "BACKUP_AGE_RECIPIENT must be one or more comma-separated age public keys (age1...); got '$recipient'"
  done
}

# Encrypts FILE with age when a recipient is configured. Prints the path to upload.
# Plaintext uploads require the explicit BACKUP_ALLOW_PLAINTEXT=1 opt-out (fail closed).
maybe_encrypt() { # FILE -> stdout: path
  local file="$1" args=() recipient
  if [ -n "${BACKUP_AGE_RECIPIENT:-}" ]; then
    validate_recipients
    for recipient in "${RECIPIENTS[@]}"; do args+=(--recipient "$recipient"); done
    age "${args[@]}" --output "$file.age" "$file" || die "age encryption failed"
    [ -s "$file.age" ] || die "age produced an empty file"
    rm -f "$file"
    printf '%s' "$file.age"
  else
    [ "${BACKUP_ALLOW_PLAINTEXT:-0}" = "1" ] || die "BACKUP_AGE_RECIPIENT is empty; refusing to upload an unencrypted dump (set BACKUP_ALLOW_PLAINTEXT=1 to override)"
    warn "uploading UNENCRYPTED dump because BACKUP_ALLOW_PLAINTEXT=1"
    printf '%s' "$file"
  fi
}

check_total_size() {
  local total
  total="$(s3_list "$(s3_prefix)/" | awk '{s += $2} END {print s + 0}')" || die "failed measuring bucket usage"
  log "bucket usage under $(s3_prefix)/ is $total bytes (limit $MAX_TOTAL_BYTES)"
  [ "$total" -le "$MAX_TOTAL_BYTES" ] || die "Object Storage usage $total bytes exceeds BACKUP_MAX_TOTAL_BYTES=$MAX_TOTAL_BYTES; shrink retention or the free-tier 20 GB will be exceeded"
}

prune_local() { # DIR
  local dir="$1"
  [ -d "$dir" ] || return 0
  # shellcheck disable=SC2012 # names are generated by this script (no spaces)
  ls -1t "$dir" 2>/dev/null | grep -E '\.dump(\.age)?$' | tail -n +"$((LOCAL_RETAIN + 1))" | while IFS= read -r old; do
    rm -f "${dir:?}/$old"
  done
}

do_backup() {
  require_env PGHOST PGUSER PGPASSWORD PGDATABASE
  s3_validate_config
  s3_configured || die "Object Storage is not fully configured"
  local stamp work payload name prefix dow
  stamp="$(date -u +%Y%m%dT%H%M%SZ)"
  work="$BACKUP_DIR/daily"
  mkdir -p "$work"
  chmod 700 "$work" 2>/dev/null || true
  name="matchday-${PGDATABASE}-${stamp}.dump"
  payload="$work/$name"

  log "starting pg_dump database=$PGDATABASE host=$PGHOST"
  if ! pg_dump --format=custom --no-owner --no-acl --file "$payload.partial"; then
    rm -f "$payload.partial"
    die "pg_dump failed"
  fi
  [ -s "$payload.partial" ] || die "pg_dump produced an empty file"
  pg_restore --list "$payload.partial" >/dev/null || die "pg_restore --list could not read the fresh dump (corrupt archive)"
  mv "$payload.partial" "$payload"

  payload="$(maybe_encrypt "$payload")"
  name="$(basename "$payload")"
  LAST_BYTES="$(size_of "$payload")"
  LAST_SHA="$(sha256_of "$payload")"

  prefix="$(s3_prefix)"
  LAST_KEY="$prefix/daily/$name"
  s3_upload_verified "$LAST_KEY" "$payload"

  dow="$(date -u +%u)" # 1=Mon .. 7=Sun (UTC); weekly copy is taken on BACKUP_WEEKLY_DAY (default Sunday)
  if [ "$dow" = "${BACKUP_WEEKLY_DAY:-7}" ]; then
    s3_upload_verified "$prefix/weekly/$name" "$payload"
  fi

  s3_prune "$prefix/daily/" "$RETAIN_DAILY"
  s3_prune "$prefix/weekly/" "$RETAIN_WEEKLY"
  s3_prune "$prefix/premigration/" "$RETAIN_PREMIGRATION"
  check_total_size
  prune_local "$work"
  SUCCEEDED=1
}

do_upload_snapshot() {
  local file="${1:-}"
  [ -n "$file" ] && [ -f "$file" ] || die "upload-snapshot requires an existing dump file"
  s3_validate_config
  local work payload name
  work="$BACKUP_DIR/snapshot-work"
  mkdir -p "$work"
  name="$(basename "$file")"
  cp "$file" "$work/$name"
  payload="$(maybe_encrypt "$work/$name")"
  LAST_BYTES="$(size_of "$payload")"
  LAST_SHA="$(sha256_of "$payload")"
  LAST_KEY="$(s3_prefix)/premigration/$(basename "$payload")"
  s3_upload_verified "$LAST_KEY" "$payload"
  rm -f "$payload"
  s3_prune "$(s3_prefix)/premigration/" "$RETAIN_PREMIGRATION"
  SUCCEEDED=1
}

case "$COMMAND" in
  backup) do_backup ;;
  upload-snapshot) do_upload_snapshot "${2:-}" ;;
  *) die "unknown command '$COMMAND' (expected: backup | upload-snapshot FILE)" ;;
esac
